#!/bin/sh
# vol=35

# wait for mpv to load before continuing so the commands aren't sent to a black hole
# while true; do [ -n "$( echo '{ "command": ["get_property", "pid"] }' | socat - /tmp/mpvsocketytmp )" ] && break; sleep .2; done >/dev/null 2>&1

# the four lines below are toggled by the ytmpsuite script; don't change the comments
# (feel free to change the commands or move the comment and command to a different place
# but be sure to leave a space after the # and put the cmds directly below the comments)
# or else the toggle system won't work

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp && exit

# ytmp -vl $vol && exit

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT ALT
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp && mpv_socket_commands s loop true && exit

# ytmp -vl $vol && ytmp -l && exit

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT 1
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT 2
# mpv_socket_commands s loop true st /tmp/mpvsocketytmp

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT MASTER
# if [ "$( ytmpsuite gt1 | tail -1 )" = 'ON' ] || [ "$( ytmpsuite gt2 | tail -1 )" = 'ON' ]; then exit; fi

# if /tmp/mpvsocketytmp is not the socket in /tmp/active_mpvsocket (i.e. the active socket for the mpv_socket_commands script) check if it's the only socket open; if it is, make it the active socket.
# [ "`cat /tmp/active_mpvsocket`" = '/tmp/mpvsocketytmp' ] || ( mpv_socket_commands k; [ "`grep -c . /tmp/current_mpvsockets`" = '1' ] && echo '/tmp/mpvsocketytmp' > /tmp/active_mpvsocket )

ifytmpactive () {
	if [ "`cat /tmp/active_mpvsocket`" = '/tmp/mpvsocketytmp' ]; then
		break
	else
		# if /tmp/mpvsocketytmp is not the active socket, lower the volume
		mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp
		# ytmp -vl $vol
	fi
}

# if -d -r -n options are not running, loop; otherwise don't.
# ( ! pgrep -f 'ytmp (-d|-r|-n)+' ) && echo '{ "command": ["set_property", "loop", true ] }' | socat - /tmp/mpvsocketytmp || echo '{ "command": ["set_property", "loop", false ] }' | socat - /tmp/mpvsocketytmp
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp && exit || ifytmpactive
# ifytmpactive
# echo '{ "command": ["set_property", "loop", true ] }' | socat - /tmp/mpvsocketytmp
# ytmp -l
