#!/bin/sh
vol=35

# wait for mpv to load before continuing so the commands aren't sent to a black hole
while true; do [ -n "$( echo '{ "command": ["get_property", "pid"] }' | socat - /tmp/mpvsocketytmp )" ] && break; done >/dev/null 2>&1

# the two lines below are toggled by the ytmpsuite script; don't change the comments 
# (feel free to change the commands - make sure to leave a space after the # and leave them directly below the comments) 
# or else the toggle system won't work

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp && exit

# LINE BELOW IS TOGGLED BY AN EXTERNAL SCRIPT ALT
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp && mpv_socket_commands s loop true && exit

# if /tmp/mpvsocketytmp is not the socket in /tmp/active_mpvsocket (i.e. the active socket for the mpv_socket_commands script) check if it's the only socket open; if it is, make it the active socket.
[ "`cat /tmp/active_mpvsocket`" = '/tmp/mpvsocketytmp' ] || ( mpv_socket_commands k; [ "`grep -c . /tmp/current_mpvsockets`" = '1' ] && echo '/tmp/mpvsocketytmp' > /tmp/active_mpvsocket )

ifytmpactive () {
	if [ "`cat /tmp/active_mpvsocket`" = '/tmp/mpvsocketytmp' ]; then
		break
	else
		# if /tmp/mpvsocketytmp is not the active socket, lower the volume
		mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp		
	fi
}

# if -d -r -n options are not running, loop; otherwise don't.
( ! pgrep -fa 'ytmp -d' ) && ( ! pgrep -fa 'ytmp -r' ) && ( ! pgrep -fa 'ytmp -n' ) && echo '{ "command": ["set_property", "loop", true ] }' | socat - /tmp/mpvsocketytmp || echo '{ "command": ["set_property", "loop", false ] }' | socat - /tmp/mpvsocketytmp
# mpv_socket_commands s volume $vol st /tmp/mpvsocketytmp && exit || ifytmpactive
ifytmpactive
# echo '{ "command": ["set_property", "loop", true ] }' | socat - /tmp/mpvsocketytmp
