#!/bin/sh
conf="/home/$USER/Music/ytmp/conf"
mpvsocket='/tmp/mpvsocketytmp'
. $conf
playing_regex="^\([^ ]\{11,12\}\) \($playing_ind\)\(.*\)\($closing_playing_ind\)\( *$tag_char.*\)\?$"
field_regex="^\([^ ]\{11,12\}\) \([^$tag_char]*\)\( $tag_char.*\)\?"
case "$1" in
	 -gp) mpv_socket_commands g pause st "$mpvsocket" | jq -r .data ;;
	 -gl) [ `mpv_socket_commands g loop st "$mpvsocket" | jq -r .data` = inf ] && printf '󰑖' || printf '󰑗' ;;
	 -tl) [ `mpv_socket_commands g loop st "$mpvsocket" | jq -r .data` = inf ] && mpv_socket_commands s loop false st "$mpvsocket" || mpv_socket_commands s loop true st "$mpvsocket" ;;
	 -gd) pgrep -f 'ytmp -d$' >/dev/null 2>&1 && echo 1 || echo 0 ;;
	 -gr) pgrep -f 'ytmp -r$' >/dev/null 2>&1 && echo 1 || echo 0 ;;
	 -td) pgrep -f 'ytmp -d$' >/dev/null 2>&1 && pkill -f 'ytmp -d' || ytmp -d ;;
	 -tr) pgrep -f 'ytmp -r$' >/dev/null 2>&1 && pkill -f 'ytmp -r' || ytmp -r ;;
	 -prev) grep -B 1 "$playing_regex" "$queue" | sed -n "1s/$field_regex/\2/p" ;;
	 -title) sed -n "s/$playing_regex/\3/p" "$queue" ;;
	 # -title) mpv_socket_commands g media-title st "$mpvsocket" | jq -r .data | sed -E 's/[^ ]{11,12} //' ;;
	 -next) grep -A 1 "$playing_regex" "$queue" | sed -n "2s/$field_regex/\2/p" ;;
esac
