#!/bin/sh
[ "$1" = '-t' ] && target="$2" && shift 2 || target=ytmp
[ "$1" = c ] && setsid -f termux-notification-remove "${target}but" >/dev/null 2>&1 && setsid -f termux-notification-remove "${target}med" >/dev/null 2>&1 && exit

altbindfile='/data/data/com.termux/files/home/storage/shared/Music/ytmp/.cache/altbindfile'

#stat -c '%W' "$altbindfile"

case "$1" in
	b1) [ -e "$altbindfile" ] && rm -f "$altbindfile" && set -- press '4/' || set -- press / ;; #shell /data/data/com.termux/files/home/bin/termux-url-opener termux ;;
	b2) [ -e "$altbindfile" ] && rm -f "$altbindfile" && set -- press 7 || set -- press - ;;
	b3) [ -e "$altbindfile" ] && rm -f "$altbindfile" && set -- press 0 || set -- press 5 ;;
	m1) [ -e "$altbindfile" ] && rm -f "$altbindfile" || touch "$altbindfile" ;;
	m2) [ -e "$altbindfile" ] && rm -f "$altbindfile" && set -- press 'C-RIGHT' || set -- press 'Space' ;;
	m3) [ -e "$altbindfile" ] && rm -f "$altbindfile" && set -- press 'C-LEFT' || set -- press 'Q' ;;
	m4) [ -e "$altbindfile" ] && rm -f "$altbindfile" && set -- next || set -- press L ;;
esac

#[ -e "$altbindfile" ] && b3name=

case "$1" in
	prev|next)
		[ "$1" = prev ] && ytmpcmd=p && nvimcmd='>' && fzfcmd=P
		[ "$1" = next ] && ytmpcmd=n && nvimcmd='>' && fzfcmd=N
		pgrep -fa 'ytmp_mpv' >/dev/null 2>&1 && tmux send-keys -t "$target" q
		while pgrep -fa 'ytmp_mpv' >/dev/null 2>&1; do sleep .1; done
		if pgrep -f '/data/data/com.termux/files/usr/bin/ytmp -(d|r)+' >/dev/null 2>&1; then 
			tmux send-keys -t "$target" q
		elif pgrep -f 'ytmp E$' >/dev/null 2>&1; then 
			tmux send-keys -t "$target" $nvimcmd
		elif pgrep -f 'ytmp v$' >/dev/null 2>&1; then 
			tmux send-keys -t "$target" $fzfcmd
		else
			tmux send-keys -t "$target" "ytmp $ytmpcmd" Enter
		fi
		;;
	#playpause) tmux send-keys -t "$target" Space ;;
	pz) sleep "$2"; ! tmux capture-pane -p -t "$target" | grep -q 'paused' && tmux send-keys -t "$target" Space; return ;;
	savequit) tmux send-keys -t "$target" Q ;;
	#loop) tmux send-keys -t "$target" L ;;
	shell) shift; sh "$@" ;;
	press) tmux send-keys -t "$target" "$2" ;;
	#vd) tmux send-keys -l -t "$target" '/' ;;
	#vu) tmux send-keys -l -t "$target" '-' ;;
esac

[ -n "$1" ] && sleep .1

while ! tmux capture-pane -p -t "$target" | grep -q '..:..:.. / ..:..:..'; do pgrep -fa 'ytmp_mpv' >/dev/null 2>&1 && sleep .2 || (termux-notification-remove ytmpbut; termux-notification-remove ytmpmed; exit); done

#echo "$cpane" | tail -2 | head -1 | grep -q '..:..:.. / ..:..:..' && cpane="$(echo "$cpane" | tail -3 | head -1)\n$(echo "$cpane" | sed 1d | tr -d \n)"

#pgrep -fa 'ytmp E' >/dev/null 2>&1 && cpane="$(tmux capture-pane -p -t "$target" | sed -e '$d' -e '/^[0-9]+$/d' | cut -d' ' -f2- | grep -xv \n)" || cpane="$(tmux capture-pane -p -t "$target" | grep -xv \n)"
#title="$(echo "$cpane" | tail -2 | head -1)"
#content="$(echo "$cpane" | tail -2 | sed -En '2s/^.{11}//p')"

cpane="$(tmux capture-pane -p -t "$target" | grep -B1 '..:..:.. / ..:..:..')"

title="$(echo "$cpane" | head -1)"
content="$(echo "$cpane" | tail -1 | sed -En 's/^.{11}//p')"

echo "$title" | grep -q '..:..:.. / ..:..:..' && title="$(echo "$cpane" | tail -3 | head -1)" && content="$(echo "$cpane" | tail -2 | tr -d '\n')"

[ -z "$1" ] && rm -f "$altbindfile" && termux-notification --group "$target" --type media --priority mid --ongoing --alert-once --id "${target}med" --media-pause "ytmpnotif -t $target m2" --media-previous "ytmpnotif -t $target m1" --media-play "ytmpnotif -t $target m3" --media-next "ytmpnotif -t $target m4" #--button1 "-4v" --button1-action "tmux send-keys -t "$target" 5" #--action "ytmpnotif -t $target playpause"

#[ "$target" = ytmp ] && 
termux-notification --group "$target" --priority high --ongoing --alert-once --id "${target}but" -t "$title" -c "$content" --button1 "-v/36v" --button1-action "ytmpnotif -t $target b1" --button2 "+v/70v" --button2-action "ytmpnotif -t $target b2" --button3 "50v/100v" --button3-action "ytmpnotif -t $target b3" #--action "tmux send-keys -t "$target" 0"
